### ISSUE TITLE
example code for 3D world coordinates

### ISSUE THREAD

**Issue by redorangeyellowy** [ut-vision/HANDS2023_AssemblyHands#2]
I checked that the world coordinates of 3D pose of two hands are needed to submit the test results of our model.

I wonder if I could get an example code to get it.

**Comment by tkhkaeio** [comment]
Thank you for your participation.
We don't think the a strong necessity to publish it since it depends on their own code and the process is not complicated.
We've already provided the utility function to transform across coordinate systems in the toolkit.
Please implement the inverse process of the dataloader that loads the world coords and converts it to image coords.
